// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF9zKN8M4W_swIbNo-W9kg_j5Ta6XFrZ4',
    appId: '1:193562874029:web:90a484404dde588856f624',
    messagingSenderId: '193562874029',
    projectId: 'e-commerce-application-32dc8',
    authDomain: 'e-commerce-application-32dc8.firebaseapp.com',
    storageBucket: 'e-commerce-application-32dc8.firebasestorage.app',
    measurementId: 'G-SH4XDBYC2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIb-p_N-1FNcr4CdaCZgzOKUcKhuYcXmc',
    appId: '1:193562874029:android:61f95e34a7d6440f56f624',
    messagingSenderId: '193562874029',
    projectId: 'e-commerce-application-32dc8',
    storageBucket: 'e-commerce-application-32dc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs27hYw8_5VtMOCTxyoy0CT0RS-_NcDrk',
    appId: '1:193562874029:ios:e49c36925913a95856f624',
    messagingSenderId: '193562874029',
    projectId: 'e-commerce-application-32dc8',
    storageBucket: 'e-commerce-application-32dc8.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs27hYw8_5VtMOCTxyoy0CT0RS-_NcDrk',
    appId: '1:193562874029:ios:e49c36925913a95856f624',
    messagingSenderId: '193562874029',
    projectId: 'e-commerce-application-32dc8',
    storageBucket: 'e-commerce-application-32dc8.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF9zKN8M4W_swIbNo-W9kg_j5Ta6XFrZ4',
    appId: '1:193562874029:web:8ca20a3b459806c156f624',
    messagingSenderId: '193562874029',
    projectId: 'e-commerce-application-32dc8',
    authDomain: 'e-commerce-application-32dc8.firebaseapp.com',
    storageBucket: 'e-commerce-application-32dc8.firebasestorage.app',
    measurementId: 'G-K7GHZ7V635',
  );
}
